# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rbs-inline', '~> 0.14.0', require: false
gem 'rubocop', '~> 1.91.0', require: false
gem 'rubocop-minitest', '~> 0.39.1', require: false
gem 'rubocop-performance', '~> 1.27.0', require: false
gem 'steep', '~> 2.1.0', require: false
