# frozen_string_literal: true

source 'https://rubygems.org'

gem 'rbs-inline', '~> 0.13.0', require: false
gem 'rubocop', '~> 1.86.1', require: false
gem 'rubocop-minitest', '~> 0.39.1', require: false
gem 'rubocop-performance', '~> 1.26.1', require: false
gem 'steep', '~> 2.0.0', require: false
