# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches:
      - master
    paths:
      - .github/actions/setup-ruby/action.yml
      - .github/workflows/ruby.yml
      - .ruby-version
      - ruby/**/*.rb
      - ruby/**/*.rbs
      - ruby/rubocop.yml
      - ruby/rubocop_todo.yml
      - ruby/Steepfile
  pull_request:
    paths:
      - .github/actions/setup-ruby/action.yml
      - .github/workflows/ruby.yml
      - .ruby-version
      - ruby/**/*.rb
      - ruby/**/*.rbs
      - ruby/rubocop.yml
      - ruby/rubocop_todo.yml
      - ruby/Steepfile

permissions:
  contents: read

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
      # change this to (see https://github.com/ruby/setup-ruby#versioning):
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
      - name: Install Gems
        run: gem install rubocop rubocop-minitest rubocop-performance rbs-inline steep
      - name: Run Minitest
        working-directory: ./ruby
        run: ruby test/application_test.rb
      - name: Run RuboCop
        working-directory: ./ruby
        run: rubocop
      - name: Run Steep
        working-directory: ./ruby
        run: |
          rbs-inline --output sig/generated/ .
          steep check
